/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "前端自习室",
  "description": "属于coderWorld的知识体系库",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "前端自习室",
      "frontmatter": {},
      "regularPath": "/noteBook/",
      "relativePath": "noteBook/README.md",
      "key": "v-9de0dc84",
      "path": "/noteBook/"
    },
    {
      "title": "架构",
      "frontmatter": {},
      "regularPath": "/noteBook/architecture/",
      "relativePath": "noteBook/architecture/index.md",
      "key": "v-3412424e",
      "path": "/noteBook/architecture/"
    },
    {
      "title": "算法",
      "frontmatter": {},
      "regularPath": "/noteBook/algrithum/",
      "relativePath": "noteBook/algrithum/index.md",
      "key": "v-211c1b23",
      "path": "/noteBook/algrithum/"
    },
    {
      "title": "设计厨房",
      "frontmatter": {},
      "regularPath": "/noteBook/design/",
      "relativePath": "noteBook/design/index.md",
      "key": "v-f577768e",
      "path": "/noteBook/design/"
    },
    {
      "title": "后端",
      "frontmatter": {},
      "regularPath": "/noteBook/backEnd/",
      "relativePath": "noteBook/backEnd/index.md",
      "key": "v-2e4f7ab9",
      "path": "/noteBook/backEnd/"
    },
    {
      "title": "前端",
      "frontmatter": {},
      "regularPath": "/noteBook/design/frontEnd/",
      "relativePath": "noteBook/design/frontEnd/index.md",
      "key": "v-37b4eae4",
      "path": "/noteBook/design/frontEnd/"
    },
    {
      "title": "源码阅读",
      "frontmatter": {},
      "regularPath": "/noteBook/code_reading/",
      "relativePath": "noteBook/code_reading/index.md",
      "key": "v-653dc08e",
      "path": "/noteBook/code_reading/"
    },
    {
      "title": "设计厨房",
      "frontmatter": {},
      "regularPath": "/noteBook/design/kitchen/",
      "relativePath": "noteBook/design/kitchen/index.md",
      "key": "v-67ca7ae8",
      "path": "/noteBook/design/kitchen/"
    },
    {
      "title": "工作经验",
      "frontmatter": {},
      "regularPath": "/noteBook/experience/",
      "relativePath": "noteBook/experience/index.md",
      "key": "v-0a58e239",
      "path": "/noteBook/experience/"
    },
    {
      "title": "登录",
      "frontmatter": {},
      "regularPath": "/noteBook/experience/login.html",
      "relativePath": "noteBook/experience/login.md",
      "key": "v-62021ae0",
      "path": "/noteBook/experience/login.html"
    },
    {
      "title": "前端",
      "frontmatter": {},
      "regularPath": "/noteBook/frontEnd/",
      "relativePath": "noteBook/frontEnd/index.md",
      "key": "v-52bad3b9",
      "path": "/noteBook/frontEnd/"
    },
    {
      "title": "git",
      "frontmatter": {},
      "regularPath": "/noteBook/git/",
      "relativePath": "noteBook/git/index.md",
      "key": "v-25ee7006",
      "path": "/noteBook/git/"
    },
    {
      "title": "运维",
      "frontmatter": {},
      "regularPath": "/noteBook/operate/",
      "relativePath": "noteBook/operate/index.md",
      "key": "v-aab106ce",
      "path": "/noteBook/operate/"
    },
    {
      "title": "其他",
      "frontmatter": {},
      "regularPath": "/noteBook/others/",
      "relativePath": "noteBook/others/index.md",
      "key": "v-7a7df5ce",
      "path": "/noteBook/others/"
    },
    {
      "title": "编程利器",
      "frontmatter": {},
      "regularPath": "/noteBook/resources/",
      "relativePath": "noteBook/resources/index.md",
      "key": "v-8bfb17d2",
      "path": "/noteBook/resources/"
    },
    {
      "title": "sql",
      "frontmatter": {},
      "regularPath": "/noteBook/sql/",
      "relativePath": "noteBook/sql/index.md",
      "key": "v-44b43005",
      "path": "/noteBook/sql/"
    },
    {
      "title": "生活不止代码",
      "frontmatter": {},
      "regularPath": "/withoutCode/",
      "relativePath": "withoutCode/README.md",
      "key": "v-63663d9c",
      "path": "/withoutCode/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "技术笔记",
        "link": "/noteBook/"
      },
      {
        "text": "生活不止代码",
        "link": "/withoutCode/"
      },
      {
        "text": "关于码外生活",
        "items": [
          {
            "text": "Github",
            "link": "https://github.com/8ecomeDreamer"
          },
          {
            "text": "掘金",
            "link": "https://juejin.cn/user/2331413035352680"
          }
        ]
      }
    ],
    "sidebar": {
      "/noteBook/": [
        {
          "title": "站点介绍",
          "path": "/noteBook/",
          "collapsable": true,
          "children": []
        },
        {
          "title": "设计",
          "path": "/noteBook/design/",
          "collapsable": false,
          "sidebarDepth": 5,
          "children": []
        },
        {
          "title": "前端",
          "path": "/noteBook/frontEnd/",
          "collapsable": false
        },
        {
          "title": "后端",
          "path": "/noteBook/backEnd/",
          "collapsable": false
        },
        {
          "title": "sql",
          "path": "/noteBook/sql/",
          "collapsable": false
        },
        {
          "title": "git",
          "path": "/noteBook/git/",
          "collapsable": false
        },
        {
          "title": "算法",
          "path": "/noteBook/algrithum/",
          "collapsable": false
        },
        {
          "title": "运维",
          "path": "/noteBook/operate/",
          "collapsable": false
        },
        {
          "title": "源码阅读",
          "path": "/noteBook/code_reading/",
          "collapsable": false,
          "children": []
        },
        {
          "title": "工作经验",
          "path": "/noteBook/experience/",
          "collapsable": false,
          "children": []
        },
        {
          "title": "优秀资源",
          "path": "/noteBook/resources/",
          "collapsable": false,
          "children": []
        },
        {
          "title": "其他",
          "path": "/noteBook/others/",
          "collapsable": false
        }
      ],
      "/withoutCode/": [
        {
          "title": "生活不止代码",
          "path": "/withoutCode/",
          "collapsable": true
        }
      ],
      "/": [
        ""
      ]
    }
  }
}