/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "前端自习室",
  "description": "属于coderWorld的知识体系库",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-535dffbe",
      "path": "/guide/"
    },
    {
      "title": "前端自习室",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-479ad4ab",
      "path": "/"
    }
  ],
  "themeConfig": {}
}